### ISSUE TITLE
Allow captured identifiers in format strings

### ISSUE THREAD

**Issue by Nagidal** [rust-lang/rust-playground#908] opened 2023-03-17 07:23 UTC
Format strings can capture arguments simply by writing `{ident}` in the string, since 1.58.0 stable. ([Announced](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings) in rust blog)

This works in Rust now:

```rust
// https://stackoverflow.com/a/70504075/9235421

fn main() {
    let msg = "here";
    let s = format!("Abc {msg}");  
    println!("Hi t{msg}");   // prints "Hi there"
    println!("{s}");         // prints "Abc here" 
}
```
But in Rust Playground it throws this error:

> Response was not JSON: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Also, Rust Playground provides no sharable link to such a playground.

**Comment by shepmaster** [comment] 2023-03-17 11:48
It does, there's just a current operational issue. Duplicate of #910

**Closed by shepmaster** 2023-03-17 11:48 UTC
Labels: wontfix
