### ISSUE TITLE
Could not start the container

### ISSUE THREAD

**Issue by MizardX** [rust-lang/rust-playground#1016] opened 2023-12-09 19:53 UTC
When trying to execute some code on https://play.rust-lang.org/ I just got a blank screen. No output at all.

```rust
fn main() {
    println!("X");
}
```

Looking in the console, I noticed a POST request that resulted in HTTP 500 error:
> Unable to perform a streaming execute: Could not begin the execution session: Could not start the container: Unable to load original Cargo.toml: Could not read the file: Did not receive a response from the demultiplexer: channel closed

This error was not shown on the page, unless I switched to one of the alternative outputs (ASM, LLVM IR, MIR, HIR or WASM):
![image](https://github.com/rust-lang/rust-playground/assets/277403/078b4648-a9d0-416c-816c-6de581965f89)

Switching to Stable or Beta channel does not work either.

Whatever I try, that message seems to repeat.

**Comment by Taxolotl** [comment] 2023-12-09 23:26
I'm having this same issue. I am pretty sure it's a server problem.

**Comment by Taxolotl** [comment] 2023-12-10 00:17
![image](https://github.com/rust-lang/rust-playground/assets/112824633/5a2a6f08-4c45-4694-a2da-2a72c55a2cd6)
This is the output from attempting to run code in rust by example with the run button

**Comment by lioriz1** [comment] 2023-12-10 07:05
Came back for life

**Comment by MizardX** [comment] 2023-12-10 10:21
Seems to be working again. We'll see if this persists. I have no idea what happened.
![image](https://github.com/rust-lang/rust-playground/assets/277403/afff9592-7d94-4289-ab3e-b957f08bde7e)

**Comment by shepmaster** [comment] 2023-12-10 14:21
Duplicate of #955

**Closed by shepmaster** 2023-12-10 14:21 UTC
