### ISSUE TITLE
Trying to run the code examples from Book and Rust-by-example frequently result in lots of errors

### ISSUE THREAD

**Issue by eduarddejong** [rust-lang/rust-playground#1018] opened 2023-12-10 14:07 UTC
See the screenshot below (sorry for some Dutch language, I will clarify things if desirable).
This is my experience using Firefox (on Linux).
I now decided to open de dev tools console to see what errors it's reporting, and it's not good.

I know these books are clearly using the Playground via some API, that's why I am reporting it here and not for each of those books.

Also note that the first time I noticed those timeout problems was close to the beginning this year, when I was reading the Book for the first time. So my impression is that the problems are not new at all.

But what I now noticed is that in many cases the Ctrl+Enter also fails to execute completely (nothing happens), while pressing the run button with the mouse still works.

![afbeelding](https://github.com/rust-lang/rust-playground/assets/86660027/c363e6d8-8678-41b2-a971-b9ac61b74c10)

**Comment by shepmaster** [comment] 2023-12-10 14:21
Duplicate of #955

**Closed by shepmaster** 2023-12-10 14:21 UTC
