### ISSUE TITLE
Can't run / build any code (Unexpected token '<', "<!DOCTYPE "... is not valid JSON)

### ISSUE THREAD

**Issue by MelonenBiber** [rust-lang/rust-playground#1017] opened 2023-12-10 13:36 UTC
### How to reproduce:
1. Visit https://play.rust-lang.org/ in a private window (default configurations & example code)
2. Click the "RUN" button

### Beheaviour
execution progress loads for 30-45 seconds then errors out.
Error message on ungoogled-chromium: `Unexpected token '<', "<!DOCTYPE "... is not valid JSON`
Error message on firefox: `JSON.parse: unexpected character at line 1 column 1 of the JSON data`

### Additional info
Chrome version: 119.0.6045.199 (Official Build, ungoogled-chromium) (64-bit) 
Firefox version: 120.0 (64-bit)

**Comment by shepmaster** [comment] 2023-12-10 14:21
Duplicate of #955

**Closed** 2023-12-10 14:20 UTC
